### ISSUE TITLE
Algolia Search does not bring any results

### ISSUE THREAD

**Issue by luisfelipesdn12** [slidevjs/docs-br#2]
Locally, I've tried to change the language code to `en` and `fr` and both of them worked.
But `pt`, `pt-br` or `pt-BR` does not bring any result.

File: [.vitepress/config.js in line 228](https://github.com/slidevjs/docs-br/blob/main/.vitepress/config.js#L228)

**Comment by antfu** [comment]
I have just configured the crawler a few hours ago, try with `br`?

**Comment by luisfelipesdn12** [comment]
> I have just configured the crawler a few hours ago, try with `br`?

yay, thank you
It worked
